### ISSUE TITLE
"invalid signature" decoding unsplash png

### ISSUE THREAD

**Issue by johnspurlock** [denosaurs/pngs#1]
Calling `decode` on the following png fails to decode with "invalid signature".  It works on other pngs.

Looks like a png to me, am I missing something obvious?

https://images.unsplash.com/photo-1636014470337-fd160bee5530?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&fm=png&fit=crop&w=234

![unsplash](https://user-images.githubusercontent.com/528937/149007028-9c073c04-cb1f-487b-b903-f281bbcb57c5.png)

Thanks!

**Comment by eliassjogreen** [comment]
```ts
import { decode } from "https://deno.land/x/pngs/mod.ts";
const file = new Uint8Array(await (await fetch("https://images.unsplash.com/photo-1636014470337-fd160bee5530?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&fm=png&fit=crop&w=234")).arrayBuffer());
console.log(decode(file));
```
works fine for me, perhaps you have a corrupted file or downloaded a different format?

**Comment by johnspurlock** [comment]
Sorry, I'm trying to get this working in a Cloudflare Worker, and was not escaping the url, hence unsplash returned a jpg to me on Cloudflare. 

Got it working (!) on pngs under a certain size (~10mb array)

For larger ones, I'm hitting a different error (only on Cloudflare, not locally)

```
RuntimeError: unreachable
    at wasm://wasm/0009451e:wasm-function[83]:0x1bd7d
    at wasm://wasm/0009451e:wasm-function[9]:0xd150
    at decode (main:2665:21)
    at decode1 (main:2777:17)
    at computeImg (main:2806:23)
    at async Object.fetch (main:2964:20)
```

Any idea what that indicates?  It's not a traditional cloudflare oom error, rather some condition hit in the wasm logic.

Not sure how to debug this - guess I'll cap the input example image size for my demo in the meantime

**Comment by eliassjogreen** [comment]
Could possibly be a cap in Cloudflare Workers but it could also be an issue with [denosaurs/urlpattern](https://github.com/denosaurs/urlpattern) or this module.

**Comment by johnspurlock** [comment]
Looks like a stack trace into a wasm module, so probably this png module, not urlpattern - but since it works fine locally, I'll chalk it up to something different on Cloudflare Workers.

Wish I had some sort of clue about where its failing.  Is there a way to enable debug symbols or something in wasm?

**Comment by johnspurlock** [comment]
The `RuntimeError: unreachable at wasm://wasm/0009451e:wasm-function[83]:0x1bd7d...` issue only happens when processing larger images in Cloudflare Workers in the cpu-constrained "bundled" model.  Using "unbound" workers, I no longer get this error, but can still run out of memory since they are capped to 128mb per isolate, but that's not due to this module.

Going to presume whatever cpu-limiter Cloudflare has in its constrained runtime is what early exits / makes wasm hit unreachable segments.
