### ISSUE TITLE
Possibility to get / set a pixel of the image

### ISSUE THREAD

**Issue by cristian-5** [denosaurs/pngs#2]
I would love to have a `getPixel(x, y)` method that returns `{ r, g, b, a }` and of course `setPixel({ r, g, b, a })`.

**Comment by eliassjogreen** [comment]
To do that you would simply run the `decode` function on your input png, then set the corresponding rgba values in the `DecodeResult.image` buffer (that would be `DecodeResult.image[x + y * DecodeResult.width]` plus 0, 1, 2 or 3 depending on if you want to set the R, G, B or A value) and re-encode it using the `encode` function and the correct options (mainly RGBA as the color type and the correct width and height values).

**Comment by eliassjogreen** [comment]
Also you would need to make sure that the `DecodeResult.colorType` and `DecodeResult.bitDepth` is the correct ones for RGBA 8 bit images, but in most cases that should be the case.
